### ISSUE TITLE
prefix methods with class name

### ISSUE THREAD

**Issue by johnyf** [johnyf/pyan#4]
Currently, only method names are shown. This causes confusion:

- cannot distinguish methods from functions of the same name
- cannot distinguish between methods with the same name but of different classes (magic methods are a common example)

So, instead of showing `__and__`, it should be `ClassName.__and__`.

**Comment by Technologicat** [comment]
Using `--grouped` helps a bit; the namespace is then written into the title of the group the node appears in.

In my Python 3 fork, there is now also an `--annotated` option that will add the namespace information into the node label when grouping is off. (Additionally, this option always includes source file and line number information into the node labels.)

**Comment by johnyf** [comment]
Thank you for implementing this! I tried with https://github.com/Technologicat/pyan/commit/70d7e08d2f1939944ee735aeb12a20e136e57504 and the output has improved compared to the previous version of `pyan` (26faced4edcd2bbe3f0672d6b96d7fbb2099624e).

I would like to suggest the following (from experience from https://github.com/johnyf/pycflow2dot): to consider placing the annotation in a separate table, with unique indices labeling each node to point to the table entry. This will keep the graph smaller, and easier to navigate (otherwise as the subpackage depth in a package grows, so will the node sizes, for example using `pyan` with a large package like `scipy`, `matplotlib`, or `networkx`).

Perhaps only the file name and line could still be listed below, in parentheses (as it is done now, but without the path prefix, and without the namespace). Putting the class name in front of a method name may be helpful (e.g., `Operator.support`). In any case though, https://github.com/Technologicat/pyan/commit/70d7e08d2f1939944ee735aeb12a20e136e57504 correctly identifies additional methods (e.g., previously I didn't see nodes for the `__init__` methods).

I should also note that the newer version (https://github.com/Technologicat/pyan/commit/70d7e08d2f1939944ee735aeb12a20e136e57504) shows me an edge that does not correspond to a call. In particular, and edge from the method `Operator.support` (https://github.com/johnyf/omega/blob/d63b1b3ad9d110748292400cae3d2d04788d8be8/omega/symbolic/fol.py#L492) to `Context.support` (https://github.com/johnyf/omega/blob/d63b1b3ad9d110748292400cae3d2d04788d8be8/omega/symbolic/fol.py#L150). Even though this is indeed the intended call, this information is not present in the class `Operator` (https://github.com/johnyf/omega/blob/d63b1b3ad9d110748292400cae3d2d04788d8be8/omega/symbolic/fol.py#L488), because the keyword argument `'fol'` could be an instance of some arbitrary class (even one without a method called `support`).

**Comment by Technologicat** [comment]
Hmm, could be useful to format it like that. I might look into this later - any pointers on how to do that in the `.dot` language? Any specific part of the documentation I should look at?

The `__init__()` methods were previously missing, because https://github.com/johnyf/pyan/commit/26faced4edcd2bbe3f0672d6b96d7fbb2099624e collapsed them away; see `visit_FunctionDef()`. In the Python 3 fork, I have disabled this special handling of `__init__()`, because the `__init__` namespace needs to be accounted for in order to properly support lexical scoping.

(As `symtable` indeed tells us; if interested, check the output of `analyze_scopes()` in the Python 3 fork. The `--very-verbose` option prints the currently known scopes when it starts analyzing each file, although it doesn't show the names and their currently inferred values.

In the code, this information is available in the `self.scopes` dictionary in `analyzer.py`. `None` means no value has yet been inferred; either no binding for that name has been seen yet, or either the binding syntax or the value being bound was not understood by Pyan.)

As for the last part, the *arbitrary class* may be the key observation. It sounds like the analyzer doesn't quite know what `.support()` the code is talking about, so it creates a wildcard to `*.support`, which is then resolved in the postprocessing step, by `expand_unknowns()`, to all nodes in any namespace that match the name `support`.

I have changed this logic slightly - the Python 3 fork should generate fewer spurious uses edges in general - but methods of arbitrary classes are difficult to reason about statically, indeed because Python is duck-typed. This is one reason why the README says *approximate* call graphs :)

**Comment by johnyf** [comment]
About the listing, I was actually thinking of a table outside `.dot`. In [`pycflow2dot`](https://github.com/johnyf/pycflow2dot) I have the option of generating multiple call graphs, and producing a LaTeX document from them with links from calles to callees that span different pages, via `hyperref`. So the table could be a separate text file, and potentially in the future a LaTeX file with hyperlinks from the graph to the table.

Regarding the approximate character of the inferred call graph, perhaps the degree of confidence of the tool about whether each edge is indeed a call could be recorded (I have [`vulture`](https://github.com/jendrikseipp/vulture) in mind, which identifies unused variables / unused code, and has a `--min-confidence` option). The user could select the confidence level, or the tool could also plot edges that it is unsure about with a different line style (and edges it is sure about with, say, solid lines).

**Comment by Technologicat** [comment]
Good point, the graph is not the only possible output target :)

I'm mainly viewing the output from Pyan using [my custom fork of xdot](https://yousource.it.jyu.fi/jjrandom2/miniprojects/trees/master/refactoring/xdot) from a couple of years back, which provides interactive highlighting and searching - this is why I prefer to have all the info in the node labels. Considering these different use cases, maybe there eventually needs to be an option regarding where to write what.

Confidence metric, very nice idea!

Also may be nontrivial to implement. Have to think a bit on how to define a useful metric. Completely sure cases are trivial, as are completely tentative ones (e.g. wildcard expansion), but in which specific situations would we get something in between, and how to determine a meaningful quantitative result for such cases needs some thought.

For example, to which degree should we trust inherited attributes? And should the confidence be decreased if Pyan detects a new value is being assigned to a name (in the name namespace) at some point of the analysis? (This is a bit tricky - any previous uses edges have already been added, so they need to be looked up in some robust manner in order to adjust their confidence level.)

I wasn't aware of `vulture` (there seems to be a lot of Python instrumentation these days?), thanks for the link!

**Comment by johnyf** [comment]
I think that two levels of confidence ("definitely", "maybe") would be good as a start, because they would indicate which edges may be spurious. If not completely sure, then an edge would be classified as "maybe" (to be conservative). I agree that a quantitative confidence categorization would be difficult and subjective, and probably also sensitive to little details. A binary classification though is unambiguous.

Following the example of linters (`pylint`, `pyflakes`), instead of a level of confidence, there could be options of what criteria to use and which not (so including / excluding certain kinds of edges). Another idea would be to dump a text file that lists all the lines of code relevant to "unsure" edges, so that a developer can quickly decide whether an edge is spurious, by consulting the text file (instead of having to look into each source file separately). This could be handy when inspecting large unfamiliar projects. We could think of the dumped file as "evidence" of why `pyan` thinks a call exists. Another idea is to dump links to the relevant lines in a GitHub repository, enabling easy navigation.

**Comment by Technologicat** [comment]
TODO added for confidence level (some commits back). Binary confidence sounds like a good simplification. It's still nontrivial to get right in the analysis, so for now I'm postponing it for later. (It's however very interesting, so when/if I find the time, I might look into it.)

As for the output, as this is not a top priority for me currently - if you want to experiment on it yourself, here are the main points:

See `from_visitor()` in `visgraph.py`, which chooses the `labeler` based on the options it is given.

The implementations come from `class Node` in `node.py`. The methods `get_short_name()`, `get_annotated_name()` and `get_long_annotated_name()` are meant for generating human-readable labels.

Some points of danger: the seemingly similarly named `get_name()` is an important implementation detail; it returns the fully qualified name, and is used internally by the analyzer. Also, what `Node` calls "label" is actually the `id`, which is an internal label for the graphing software. (There is still some stuff in the code that should be renamed for clarity.)

For a detailed example, see how `--annotated` is implemented. First, `main.py` introduces a command-line switch, and adds the corresponding option to `graph_options`. This dictionary is then handed to `from_visitor()` in `visgraph.py`, which generates the internal representation of the concrete visualizable graph.

The markup is generated from this internal representation by the classes in `writers.py`. For just changing the label, there is no need to touch the writers - just change the `labeler` that takes a node and returns its human-readable label.

For the auxiliary output file, I would suggest implementing a new subclass of `Writer`, which walks the graph for a second time, generating the legend. See the existing writers for examples.

If the graph is in `grouped` mode, each call to `start_subgraph()` denotes the start of a new namespace. However, in non-grouped mode that doesn't work, because no subgraphs are generated.

An approach that always works is to monitor the value of `node.namespace` in `write_node()` (i.e. store the value at the end of the call, check if different at the start of the call).

The nodes are guaranteed to be sorted by namespace when the writer gets them. The first namespace, denoting module nodes, is `''` (blank string). To get a legend line for these too, it may be useful to initialize the monitoring value to `None`.

(If you add a new labeling variant, feel free to send a PR.)

**Comment by johnyf** [comment]
Thank you for the design outline. I intend to develop things in this area in the future (though it may be some time before it happens).
