### ISSUE TITLE
I'm using pyan.py across two modules, the digraph generated seems to be wrong if the same function names are there in the two modules

### ISSUE THREAD

**Issue by priyavenky** [johnyf/pyan#5]

**Comment by johnyf** [comment]
Sounds similar to #1, may have the same cause.

**Comment by priyavenky** [comment]
All the other edges are correct, except for this test case

**Comment by Technologicat** [comment]
Is there a minimal working (non-working) example? I could look into this now that I'm at it.

From what I can tell off the top of my head, this can occur due to expansion of unknown nodes (nodes with `namespace is None`, shown in the `-v` messages as `*.name`), if the analyzer did not pick up one of the identifiers for some reason.

Specifically, this could happen for forward references (considered across the set of files being analyzed, so which references are considered forward depends on the order the files are read in).

I've changed my Python 3 fork so that the analyzer removes the wildcard `*.name`, if the second pass knows of a matching node `X.name`. See the use sites of `remove_wild()` in `analyzer.py`.

However, the current approach is not completely bulletproof. A resolved reference to `X.name` in a function (technically, namespace) will delete the wildcard `*.name` in that function, even if the wildcard was also generated by `Y.name`, where `Y` remains unresolved.

To fix this, we would need to store some information in the wildcard about the context it appeared in; perhaps mainly, make a second type of wildcard specifically for attribute references, which stores the full text of the original reference.

**Comment by priyavenky** [comment]
Hello
I am currently busy with my research. can i get back to u after my work completes.
thank you.


G Priyalakshmi, 
Assistant Professor (Selection Grade), 
Department of Applied Mathematics and Computational Sciences 
PSG College of Technology,
Coimbatore. 

    On Wednesday, November 15, 2017, 4:57:13 PM GMT+5:30, Technologicat <notifications@github.com> wrote:  
 
 
Is there a minimal working (non-working) example? I could look into this now that I'm at it.

From what I can tell off the top of my head, this can occur due to expansion of unknown nodes (nodes with namespace is None, shown in the -v messages as *.name), if the analyzer did not pick up one of the identifiers for some reason.

Specifically, this could happen for forward references (considered across the set of files being analyzed, so which references are considered forward depends on the order the files are read in).

I've changed my Python 3 fork so that the analyzer removes the wildcard *.name, if the second pass knows of a matching node X.name. See the use sites of remove_wild() in analyzer.py.

However, the current approach is not completely bulletproof. A resolved reference to X.name in a function (technically, namespace) will delete the wildcard *.name in that function, even if the wildcard was also generated by Y.name, where Y remains unresolved.

To fix this, we would need to store some information in the wildcard about the context it appeared in; perhaps mainly, make a second type of wildcard specifically for attribute references, which stores the full text of the original reference.
